### ISSUE TITLE
カスタムtemplateの追加

### ISSUE THREAD

**Issue by cutmail** [cookpad/license-tools-plugin#15]
## 概要

`checkLicenses`タスクによって出力された内容をlicenses.ymlに記載し、
再度`checkLicenses`のあとに`generateLicensePage`を実行したところ下記のようなエラーが表示された。

``` sh
* What went wrong:
Execution failed for task ':app:generateLicensePage'.
> File not found: template/licenses/Answers Terms of Service.html
```

また、licenseを`apache2`に変更しても、

``` sh
# Licenses not matched with pom.xml in dependencies:
- artifact: com.crashlytics.sdk.android:answers:1.3.6
  license: Answers Terms of Service
:app:checkLicenses FAILED
```

と表示され、`pom.xml` と一致しないと怒られてしまう。
### licenses.ymlの一部抜粋

``` yml
- artifact: com.crashlytics.sdk.android:answers:+
  name: Android SDK Answers
  copyrightHolder: Twitter Inc.
  license: Answers Terms of Service
- artifact: com.crashlytics.sdk.android:crashlytics:+
  name: Android SDK Crashlytics
  copyrightHolder: Twitter Inc.
  license: Crashlytics Terms of Service
- artifact: com.crashlytics.sdk.android:crashlytics-core:+
  name: Android SDK Crashlytics Core
  copyrightHolder: Twitter Inc.
  license: Crashlytics Terms of Service
- artifact: io.fabric.sdk.android:fabric:+
  name: Android SDK Fabric
  copyrightHolder: Twitter Inc.
  license: Fabric Software and Services Agreement
```

カスタムテンプレートもしくは、`pom.xml`とのチェックを一時的に無効にできるオプションがあると解決しそう。
